### ISSUE TITLE
Add support for React v16

### ISSUE THREAD

**Issue by openjck** [mozilla/react-metrics-graphics#13]
The `peerDependencies` for this package includes React ^15.0.0-0. When React ^16.0.0 is used, react-metrics-graphics raises an error about PropTypes. This might be due to the fact that [prop-types](https://www.npmjs.com/package/prop-types) was split into its own package in React 16.

**Comment by openjck** [comment]
Here's my setup and the error that results.

**index.js**
```javascript
var React = require('react');
var MG = require('react-metrics-graphics');
```

**package.json**
```json
{
    "dependencies": {
        "react": "^16.0.0",
        "react-metrics-graphics": "^0.6.2"
    }
}
```

**Node**
```
$ node --version
v8.3.0
```

**Running**
```
$ node index
[...]/node_modules/react-metrics-graphics/lib/MetricsGraphics.js:94
  obj[propertyName] = _react2['default'].PropTypes.any;
                                                  ^

TypeError: Cannot read property 'any' of undefined
    at /Users/john-moz/inbox/tmp/node_modules/react-metrics-graphics/lib/MetricsGraphics.js:94:51
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/john-moz/inbox/tmp/node_modules/react-metrics-graphics/lib/MetricsGraphics.js:93:48)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

**Comment by wlach** [comment]
Perhaps the best approach here is just to bump the required version of react to 15.3.0 (https://github.com/facebook/prop-types#compatibility) and make proptypes a peer dependency.

If you want to create a PR for this, feel free. Otherwise I'll probably get to it eventually!

**Comment by openjck** [comment]
Just wanted to add a couple of things for future reference:

* The correct peer dependency would be [prop-types](https://www.npmjs.com/package/prop-types). Notice the dash. Confusingly, there's another node module without a dash that shouldn't be used in this case. I won't link to it here to avoid confusion.
* Users of metrics-graphics should not that just adding prop-types to their *package.json* won't be enough to fix this problem. There will also need to be changes to metrics-graphics itself.

**Comment by armenzg** [comment]
I'm hitting this.
