### ISSUE TITLE
create-react-app cannot create production build when react-metrics-graphics is being used

### ISSUE THREAD

**Issue by openjck** [mozilla/react-metrics-graphics#18]
## Steps to reproduce

1. Clone [this repo](https://github.com/openjck/bug-demo-react-metrics-graphics-18)
2. `yarn`
3. `yarn build`

## Result

create-react-app is unable to create a production build because *MetricsGraphics.js* is unable to be minfied.

Here's the output of `yarn build`:

```
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-metrics-graphics/build/MetricsGraphics.js:1:2669

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wlach** [comment]
Grump. :/ will try to find some time to look into this soon

**Comment by wlach** [comment]
Digging into this, it looks like the problem is with this chunk of code: `class n extends f.a.Component`.

Do we need to enable a babel rule?

**Comment by wlach** [comment]
Apparently we need to compile things down to es5 for them to work with create-react-app:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

@eliperelman showed me a viable workaround:

https://github.com/eliperelman/react-fout-stager/blob/master/.neutrinorc.js#L13
