### ISSUE TITLE
Module not found: Error: Cannot resolve module 'metrics-graphics' & 'metrics-graphics/dist/metricsgraphics.css'

### ISSUE THREAD

**Issue by NicolasLeBihan** [mozilla/react-metrics-graphics#22]
I'am trying to use react-metrics-graphics in my react project, i've add it with yarn, but i get error when compiling:

`18:48:58 webpack.1 | ERROR in ../~/react-metrics-graphics/build/MetricsGraphics.js
18:48:58 webpack.1 | Module not found: Error: Cannot resolve module 'metrics-graphics/dist/metricsgraphics.css' in .../node_modules/react-metrics-graphics/build
18:48:58 webpack.1 |  @ ../~/react-metrics-graphics/build/MetricsGraphics.js 1:4478-4530`

this module is very interesting & thanks for your work.

**Comment by wlach** [comment]
@NicolasLeBihan Try adding `metrics-graphics` to your project. `react-metrics-graphics` lists it as a peer dependency, so it might not be installed automatically. I may want to change that to avoid problems like this, let me think about it.

**Comment by NicolasLeBihan** [comment]
thanks you, i'have done it. And what about 'metrics-graphics/dist/metricsgraphics.css' ?

**Comment by wlach** [comment]
Installing metrics-graphics should make the css file available also. :)

**Comment by NicolasLeBihan** [comment]
ok thanks @wlach
